charts:
  - chart:
    local-instance-image: <image:tag>
    parcel-values-file: parcel-values.yaml
    configurable-values:
    - config-name: service.some.path
      description: a path to service data
      type: string
      default-value: /some/path
