charts:
    - chart:
      local-instance-image: <image:tag>
      parcel-values-file: parcel-values.yaml
      configurable-values:
          - name: service.some.path
            description: a path to service data
            label: asdfasdfa
            type: string
            default: /some/path
